
services:
  app:
    container_name: server-aws-trial
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    # Uncomment for local development:
    # volumes:
    #   - .:/app
    #   - /app/node_modules
