name: Deploy to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on a GitHub-hosted Ubuntu runner

    steps:
      # Step 1: Checkout the repo
      - name: Checkout Repo
        uses: actions/checkout@v3

        # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
            context: .
            file: ./Dockerfile
            push: true
            tags: very438084/server-aws-trial:latest

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}  # Your AWS server IP
          username: ubuntu               # SSH user on AWS instance
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}  # GitHub secret for private SSH key

      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/app/server-aws-trial
            # git pull origin main
            # npm install
            # sudo docker stop $(docker ps -q)
            # sudo docker-compose down
            # sudo docker pull very438084/server-aws-trial:latest
            # sudo docker-compose up --build -d
            # sudo docker container prune -f
            # docker build --no-cache -t very438084/server-aws-trial .
            # sudo docker run -p 3000:3000 very438084/server-aws-trial:latest
            # Pull the latest changes from the repository
            git pull origin main

            # Install project dependencies
            npm install

            # Stop and remove any running containers
            sudo docker-compose down

            # Pull the latest Docker image
            sudo docker pull very438084/server-aws-trial:latest

            # Build and start the containers with the updated image
            sudo docker-compose up --build -d

            # Clean up unused Docker containers
            sudo docker container prune -f

