name: Deploy to AWS

on:
  push:
    branches:
      - main  # Trigger action when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on a GitHub-hosted Ubuntu runner
    
    steps:
      # Step 1: Checkout the repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Step 2: Set up SSH for connecting to your AWS server
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa  # Save private key to a file
          chmod 600 ~/.ssh/id_rsa  # Ensure correct permissions
          ssh-keyscan -H 3.106.248.7 >> ~/.ssh/known_hosts  # Add the server to known_hosts

      # Step 3: Deploy your application on AWS
      - name: Deploy application on AWS
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@3.106.248.7 << 'EOF'
            cd /home/ubuntu/app  # Make sure you're in the right directory
            git pull origin main  # Pull latest changes from the main branch (if needed)
            docker-compose down  # Stop running containers (if needed)
            docker-compose up --build -d  # Rebuild and restart containers
          EOF

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: very438084/server-aws-trial:latest
