name: Deploy to AWS

on:
  push:
    branches:
      - main  # Trigger action when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on a GitHub-hosted Ubuntu runner

    steps:
      # Step 1: Checkout the repo
      - name: Checkout Repo
        uses: actions/checkout@v3

        # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
            context: .
            file: ./Dockerfile
            push: true
            tags: very438084/server-aws-trial:latest

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}  # Your AWS server IP
          username: ubuntu               # SSH user on AWS instance
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}  # GitHub secret for private SSH key

      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}  # Your AWS server IP
          username: ubuntu               # SSH user on AWS instance
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}  # GitHub secret for private SSH key
          script: |
            # Make sure the user can run Docker without sudo
            sudo usermod -aG docker ubuntu
            # Pull the latest Docker image
            docker pull very438084/server-aws-trial:latest
            # Stop running containers (if any)
            docker-compose down
            # Rebuild and restart containers
            docker-compose up -d
        