name: Deploy to AWS

on:
  push:
    branches:
      - main  # Trigger action when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on a GitHub-hosted Ubuntu runner

    steps:
      # Step 1: Checkout the repo
      - name: Checkout Repo
        uses: actions/checkout@v3

        # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
            context: .
            file: ./Dockerfile
            push: true
            tags: very438084/server-aws-trial:latest

      # Step 2: Set up SSH for connecting to your AWS server
      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}  # Your AWS server IP
          username: ubuntu               # SSH user on AWS instance
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}  # GitHub secret for private SSH key

      # Step 3: Deploy your application
      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.AWS_SSH_PRIVATE_KEY }} ubuntu@$3.106.248.7 << 'EOF'
            docker pull very438084/server-aws-trial:latest  # Pull the latest Docker image
            docker-compose down  # Stop running containers (if any)
            docker-compose up -d  # Rebuild and restart containers
          EOF

      
